backend:
  name: github
  repo: wen00033/nuxt-app # Path to your GitHub repository
  branch: master

publish_mode: editorial_workflow
media_folder: content/img
public_folder: content/public
site_url: https://selling-site.netlify.app/

collections:
  - name: "Post"
    label: "Post"
    folder: "content/post"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Starter"
    label: "Starter"
    folder: "content/starter"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "hidden" }
      - { label: "price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
  - name: "Main"
    label: "Main"
    folder: "content/main"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "hidden" }
      - { label: "price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
  - name: "Drinks"
    label: "Drinks"
    folder: "content/drinks"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "price", name: "price", widget: "number" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "hidden" }
